as yet unclassified
endOfNamesExamples
	^ EndOfNamesExamples ifNil: [ 
		EndOfNamesExamples := { 
		':levin.mozilla.org 366 pharouser2 #newbies :End of /NAMES list.'.
':hitchcock.freenode.net 366 pharo-user ##altcoins :End of /NAMES list.'.
':tolkien.freenode.net 366 pharo-user ##altcoins :End of /NAMES list.'.
':weber.freenode.net 366 pharo-user ##crypto :End of /NAMES list.'.
':levin.mozilla.org 366 pharo-user #introduction :End of /NAMES list.'.
':belew.mozilla.org 366 pharouser2 #firefox :End of /NAMES list.'.
':adams.freenode.net 366 pharo-user ##altcoins :End of /NAMES list.'.
':weber.freenode.net 366 pharo-user ##altcoins :End of /NAMES list.'.
':belew.mozilla.org 366 pharo-user #newbies :End of /NAMES list.'.
':levin.mozilla.org 366 pharouser2 #firefox :End of /NAMES list.'.
':levin.mozilla.org 366 pharo-user #firefox :End of /NAMES list.'.
':belew.mozilla.org 366 something-else #newbies :End of /NAMES list.'.
':belew.mozilla.org 366 goober46 #mozilians :End of /NAMES list.'.
':weber.freenode.net 366 pharo-user ##altcoins :End of /NAMES list.'.
':weber.freenode.net 366 pharo-user ##altcoins :End of /NAMES list.'.
':adams.freenode.net 366 pharo-user ##altcoins :End of /NAMES list.'.
':belew.mozilla.org 366 goober46 #firefox :End of /NAMES list.'.
':adams.freenode.net 366 pharo-user ##crypto :End of /NAMES list.'.
':levin.mozilla.org 366 pharo-user #firefox :End of /NAMES list.'.
':hitchcock.freenode.net 366 pharo-user ##altcoins :End of /NAMES list.'.
 } ]