as yet unclassified
joinMsgExamples
 ^ JoinMsgExamples ifNil: [ 
	JoinMsgExamples := { 
	':pharo-user!~pharo-irc@pool-71-167-39-107.nycmny.fios.verizon.net JOIN #test1'.
':vprabhu!vprabhu@moz-ol1.7o9.82.183.IP JOIN :#test1'.
':pharo-user!pharo-irc-u@moz-tghr1v.fios.verizon.net JOIN :#test2'.
':santosh!Mibbit@moz-1mnaal.oc.cox.net JOIN :#test2'.
':ggurbet!ggurbet@moz-g1h.be3.255.88.IP JOIN :#test1'.
':humperdink!~pharo-irc@pool-71-167-39-107.nycmny.fios.verizon.net JOIN #test2'.
':Robert_Zenz!Robert_Zenz@moz-eoqeo7.dynamic.surfer.at JOIN :#test2'.
':rustylerp!~rustylerp@93.176.154.252 JOIN #test1'.
':vprabhu!vprabhu@moz-ol1.7o9.82.183.IP JOIN :#test2'.
':mcoman!Instantbird@moz-afm.0l7.127.86.IP JOIN :#test1'.
':pharo-user!~pharo-irc@pool-71-167-39-107.nycmny.fios.verizon.net JOIN #test3'.
':hehehe!uid219408@gateway/web/irccloud.com/x-eknakkpbwosvbfzg JOIN #test3'.
':Standard8!Standard8@moz-1hu.vrc.166.195.IP JOIN :#test1'.
 } ].