as yet unclassified
nickMsgExamples
	^ NickMsgExamples ifNil: [ 
		NickMsgExamples := { 
		':pharo-user!~pharo-irc@pool-71-167-39-107.nycmny.fios.verizon.net NICK :humperdink'.
':ng|brblunch!sid585@moz-dokbcj.0j4i.jtu0.0101.2620.IP NICK ng'.
':bearology!~shillosop@unaffiliated/shillosopher NICK :shillo'.
':jlund!sid364@moz-nau14j.0j4i.jtu0.0101.2620.IP NICK jlund|mtg'.
':jlund!sid364@moz-nau14j.0j4i.jtu0.0101.2620.IP NICK jlund|mtg'.
':pharo-user!~pharo-irc@pool-71-167-39-107.nycmny.fios.verizon.net NICK :humperdink'.
':bearology!~shillosop@unaffiliated/shillosopher NICK :shillo'.
':jlund|mtg!sid364@moz-nau14j.0j4i.jtu0.0101.2620.IP NICK jlund'.
':pharo-user!~pharo-irc@pool-71-167-39-107.nycmny.fios.verizon.net NICK :humperdink'.
':bearology!~shillosop@unaffiliated/shillosopher NICK :shillo'.
':bearology!~shillosop@unaffiliated/shillosopher NICK :shillo'.
':bearology!~shillosop@unaffiliated/shillosopher NICK :shillo'.
':pharo-user!~pharo-irc@pool-71-167-39-107.nycmny.fios.verizon.net NICK :humperdink'.
':pharo-user!~pharo-irc@pool-71-167-39-107.nycmny.fios.verizon.net NICK :humperdink'.
':pharo-user!~pharo-irc@pool-71-167-39-107.nycmny.fios.verizon.net NICK :humperdink'.
':ng|brblunch!sid585@moz-dokbcj.0j4i.jtu0.0101.2620.IP NICK ng'.
':pharo-user!~pharo-irc@pool-71-167-39-107.nycmny.fios.verizon.net NICK :humperdink'.
':baku|away!baku@moz-tshc70.ghst.net NICK baku'.
':bearology!~shillosop@unaffiliated/shillosopher NICK :shillo'.
':ng|brblunch!sid585@moz-dokbcj.0j4i.jtu0.0101.2620.IP NICK ng'.
 }.
 ^NickMsgExamples ].