as yet unclassified
partMsgExamples
	^ PartMsgExamples ifNil: [ 
		PartMsgExamples := { 
		':fretknot_!~IceChat78@191.142.69.111.dynamic.snap.net.nz PART #test1'.
':Strangr87!~TomGFC@75-144-40-57-Atlanta.hfc.comcastbusiness.net PART ##namespace'.
':darth-cheney!~darth-che@pool-71-167-39-107.nycmny.fios.verizon.net PART ##altcoins'.
':pharo-user!pharo-irc-u@moz-tghr1v.fios.verizon.net PART #introduction'. } ]