as yet unclassified
pingMsgExamples
	^ PingMsgExamples ifNil: [ 
		PingMsgExamples := { 
		 'PING :adams.freenode.net'.
'PING :tolkien.freenode.net'.
'PING :belew.mozilla.org'.
'PING :weber.freenode.net'.
'PING :adams.freenode.net'.
'PING :tolkien.freenode.net'.
'PING :levin.mozilla.org'.
'PING :belew.mozilla.org'.
'PING :belew.mozilla.org'.
'PING :belew.mozilla.org'.
'PING :orwell.freenode.net'.
'PING :livingstone.freenode.net'.
'PING :belew.mozilla.org'.
'PING :belew.mozilla.org'.
'PING :belew.mozilla.org'.
'PING :levin.mozilla.org'.
'PING :belew.mozilla.org'.
'PING :belew.mozilla.org'.
'PING :belew.mozilla.org'.
'PING :levin.mozilla.org'.
} ]