as yet unclassified
privMsgExamples
	"Sets a list of example PRIVMSG texts"
	^ PrivMsgExamples ifNil: [ 
		PrivMsgExamples := { 
		':lxer!~lx@ip5f5bd581.dynamic.kabel-deutschland.de PRIVMSG ##altcoins :that was weeks ago'.
':Bill48105!~Bill48105@dogecoin/staff/bill48105 PRIVMSG ##altcoins :xqb you withdraw it to outside wallet that you use for something else'.
':xelra!~xelra@unaffiliated/xelra PRIVMSG ##altcoins :booyah: They''ve been discussing about how to handle Bitcoin and crypto in general this year in Davos, but mostly decided that it''s too early and they will discuss it next year again.'.
':Microbe!sid6813@gateway/web/irccloud.com/x-ynjimxaxbwswyzqf PRIVMSG ##altcoins :Anyone could do 51, if their pockets are deep enough..'.
':Wallet!~Wallet@unaffiliated/bill48105/bot/wallet PRIVMSG ##altcoins :ALowther: Your balance is 1 DOGE (0.00439668 USD)'.
':Grimcy!Forsythe@moz-c9oa2t.us.northamericancoax.com PRIVMSG #firefox :Similarly, if I want to add something before the first sentence of my message, I''ll hit up a few times, expecting the cursor to jump to the very beginning (like hitting Home), but instead, the Gmail-Hangouts window will start scrolling up.'.
':B0g4r7_!~B0g4r7@199.87.197.61 PRIVMSG ##altcoins :nerdcore, yeah well, I meant that in a more abstract sense...'.
':ALowther!~alowther@70.126.224.181 PRIVMSG ##altcoins :.soaknow 1'.
':B0g4r7_!~B0g4r7@199.87.197.61 PRIVMSG ##altcoins :I''m saying that bitmain themselves possesses (or could make and possess) enough hashpower to pull it off.'.
':Wallet!~Wallet@unaffiliated/bill48105/bot/wallet PRIVMSG pharo-user :ALowther: | 0.00001 LTC | 1 DOGE | 0 XZC |'.
':booyah!~bb@193.25.1.157 PRIVMSG ##altcoins :B0g4r7_: or if they shut down the whole "computers" thing'.
':Microbe!sid6813@gateway/web/irccloud.com/x-ynjimxaxbwswyzqf PRIVMSG ##altcoins :The idea is solid, just the problem with power distribution'.
':xelra!~xelra@unaffiliated/xelra PRIVMSG ##altcoins :booyah: They''ve been discussing about how to handle Bitcoin and crypto in general this year in Davos, but mostly decided that it''s too early and they will discuss it next year again.'.
':Mkll!Mkll@moz-7mb.sv1.155.165.IP PRIVMSG pharo-user :https://www.ghacks.net/2018/02/07/here-is-what-is-new-and-changed-in-firefox-58-0-2/'.
':nerdcore!~mike@nerdcore.net PRIVMSG ##altcoins :it''s gonna be another great year for cryptoz!! ;)'.
':booyah!~bb@193.25.1.157 PRIVMSG ##altcoins :nerdcore: what problems it caused actually?'.
':ALowther!~alowther@70.126.224.181 PRIVMSG ##altcoins :.soak'.
':xqb!~xqb@gateway/tor-sasl/xqb PRIVMSG ##altcoins :.tip xqb 10'.
':nerdcore!~mike@nerdcore.net PRIVMSG ##altcoins :Microbe: the intention is to avoid ASIC manufacturing which would overtake the entire mining operation of a single coin/algo'.
':nerdcore!~mike@nerdcore.net PRIVMSG ##altcoins :attack and cash out immediately'.
 } ].