as yet unclassified
quitMsgExamples
	^ QuitMsgExamples ifNil: [ 
		QuitMsgExamples := { 
		':cbadescu!Instantbird@moz-afm.0l7.127.86.IP QUIT :Quit: Instantbird 1.5 -- http://www.instantbird.com'.
':finkata_!~finkata@gateway/tor-sasl/finkata QUIT :Ping timeout: 255 seconds'.
':metachr0n!nobody@gateway/vpn/privateinternetaccess/metachr0n QUIT :Ping timeout: 248 seconds'.
':rustylerp!~rustylerp@93.176.154.252 QUIT :Remote host closed the connection'.
':pharo-user!~pharo-irc@pool-71-167-39-107.nycmny.fios.verizon.net QUIT :Quit: peace the fuck out'.
':zakora!zakora@moz-pfd0vo.fbx.proxad.net QUIT :Quit: WeeChat 1.9.1'.
':Karyon!~Karyon@unaffiliated/karyon QUIT :Ping timeout: 265 seconds'.
':orivej!~orivej@185.65.134.162 QUIT :Ping timeout: 276 seconds'.
':o0ignition0o!o0ignition0@moz-g7bttf.abo.wanadoo.fr QUIT :A TLS packet with unexpected length was received.'.
':darth-cheney!~darth-che@pool-71-167-39-107.nycmny.fios.verizon.net QUIT :Client Quit'.
':pharo-user!~darth-che@pool-71-167-39-107.nycmny.fios.verizon.net QUIT :Client Quit'.
':midasi!~midasi@46-127-136-251.dynamic.hispeed.ch QUIT :Ping timeout: 240 seconds'.
':SterlingBee!~SterlingB@185.43.110.4 QUIT :Ping timeout: 276 seconds'.
':FlorinMezei|3!FlorinMezei@moz-5l3.0mm.2.5.IP QUIT :Quit: KVIrc 4.2.0 Equilibrium http://www.kvirc.net/'.
':protocol_hive!~spektre@ip68-101-173-148.sd.sd.cox.net QUIT :Ping timeout: 255 seconds'.
':finkata_!~finkata@gateway/tor-sasl/finkata QUIT :Ping timeout: 255 seconds'.
':rustylerp!~rustylerp@93.176.154.252 QUIT :Remote host closed the connection'.
':pharo-user!~Karyon@unaffiliated/karyon QUIT :Ping timeout: 265 seconds'.
':FlorinMezei!FlorinMezei@moz-5l3.0mm.2.5.IP QUIT :Quit: KVIrc 4.2.0 Equilibrium http://www.kvirc.net/'.
':midasi!~midasi@46-127-136-251.dynamic.hispeed.ch QUIT :Ping timeout: 240 seconds'.
 } ]