as yet unclassified
topicMsgExamples
	^ TopicMsgExamples ifNil: [ 
		TopicMsgExamples := { 
		 ':belew.mozilla.org 332 pharo-user #introduction :Hi! We''ll help you with the basics of Mozilla Development. http://v.gd/moz_dev_intro || Ask us anything! http://v.gd/goodq || Pasting: http://pastebin.mozilla.org || Logs: http://is.gd/fVfkZg'.
':belew.mozilla.org 332 pharo-user #firefox :Firefox community & support channel || Permission isn''t needed to ask your question. If well after asking nobody responds, say "help!" or try http://support.mozilla.org || Get Firefox from http://mozilla.org/firefox || This channel is logged at https://mozilla.logbot.info/firefox'.
':orwell.freenode.net 332 pharo-irc-user #pharo :Pharo Smalltalk http://pharo.org (release 5: May 2016) â Problem? Ask & stay around for answers, or try http://stackoverflow.com/questions/tagged/pharo â Report bugs at https://pharo.fogbugz.com/default.asp?W41'.
':levin.mozilla.org 332 pharo-user #firefox :Firefox community & support channel || Permission isn''t needed to ask your question. If well after asking nobody responds, say "help!" or try http://support.mozilla.org || Get Firefox from http://mozilla.org/firefox || This channel is logged at https://mozilla.logbot.info/firefox'.
':levin.mozilla.org 332 pharouser2 #firefox :Firefox community & support channel || Permission isn''t needed to ask your question. If well after asking nobody responds, say "help!" or try http://support.mozilla.org || Get Firefox from http://mozilla.org/firefox || This channel is logged at https://mozilla.logbot.info/firefox'.
':verne.freenode.net 332 pharo-user ##altcoins :All altcoin chat is welcome, Illegal stuff, Scams and P&D bad gtfo now! |What really matters is minable coins: https://coinmarketcap.com/coins/views/filter-non-mineable/ | https://currencyroot.com | Crypto Radio: https://radiocrypto.com - https://LRN.FM |Games: https://cryptobetfair.com |Oldskool: https://mincoinforum.com | Join us on discord https://discord.gg/9Qs7dAg'.
':levin.mozilla.org 332 pharo-user #introduction :Hi! We''ll help you with the basics of Mozilla Development. http://v.gd/moz_dev_intro || Ask us anything! http://v.gd/goodq || Pasting: http://pastebin.mozilla.org || Logs: http://is.gd/fVfkZg'.
':levin.mozilla.org 333 pharo-user #firefox glob!sid619@moz-kjga13.0j4i.jtu0.0101.2620.IP 1508306276'.
':adams.freenode.net 333 pharo-user ##altcoins LinkSic!uid267310@gateway/web/irccloud.com/x-gwpuhbnvbezelabw 1516500476'.
':levin.mozilla.org 333 pharo-user #firefox glob!sid619@moz-kjga13.0j4i.jtu0.0101.2620.IP 1508306276'.
':hitchcock.freenode.net 333 pharo-user ##altcoins LinkSic!uid267310@gateway/web/irccloud.com/x-gwpuhbnvbezelabw 1516500476'.
':tolkien.freenode.net 333 pharo-user ##altcoins LinkSic!uid267310@gateway/web/irccloud.com/x-gwpuhbnvbezelabw 1516500476'.
':verne.freenode.net 333 pharo-user #pharo VitamineD 1473681565'.
':belew.mozilla.org 333 pharo-user #newbies Costenslayer!Costenslaye@moz-k3d.pv6.235.193.IP 1460975128'.} ]