as yet unclassified
partExamples
	^ PartExamples ifNil: [ 
		PartExamples := { 
		':Strangr87!~TomGFC@75-144-40-57-Atlanta.hfc.comcastbusiness.net PART #test'.
':Strangr87!~TomGFC@75-144-40-57-Atlanta.hfc.comcastbusiness.net PART #test'.
':Strangr87!~TomGFC@75-144-40-57-Atlanta.hfc.comcastbusiness.net PART #test'.
':Strangr87!~TomGFC@75-144-40-57-Atlanta.hfc.comcastbusiness.net PART #test'.
':Strangr87!~TomGFC@75-144-40-57-Atlanta.hfc.comcastbusiness.net PART #test'.
':fretknot_!~IceChat78@191.142.69.111.dynamic.snap.net.nz PART #test'.
':fretknot_!~IceChat78@191.142.69.111.dynamic.snap.net.nz PART #test'.
':Strangr87!~TomGFC@75-144-40-57-Atlanta.hfc.comcastbusiness.net PART #test'.
':pharo-user!pharo-irc-u@moz-tghr1v.fios.verizon.net PART #test'.
':Strangr87!~TomGFC@75-144-40-57-Atlanta.hfc.comcastbusiness.net PART #test'.
 } ].